//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xiaoHOUSE.Web.discuss {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtartID;
		protected global::System.Web.UI.WebControls.TextBox txtuserID;
		protected global::System.Web.UI.WebControls.TextBox txtuserName;
		protected global::System.Web.UI.WebControls.TextBox txtdisDate;
		protected global::System.Web.UI.WebControls.TextBox txtContents;
		protected global::System.Web.UI.WebControls.TextBox txtrootID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
