//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xiaoHOUSE.Web.discuss {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblartID;
	protected global::System.Web.UI.WebControls.Label lbluserID;
	protected global::System.Web.UI.WebControls.Label lbluserName;
	protected global::System.Web.UI.WebControls.Label lbldisDate;
	protected global::System.Web.UI.WebControls.Label lblContents;
	protected global::System.Web.UI.WebControls.Label lblrootID;


       
    }
}
