//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xiaoHOUSE.Web.articles {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txttitle;
		protected global::System.Web.UI.WebControls.TextBox txtcontents;
		protected global::System.Web.UI.WebControls.TextBox txtisDiscuss;
		protected global::System.Web.UI.WebControls.TextBox txtcounts;
		protected global::System.Web.UI.WebControls.TextBox txtartType;
		protected global::System.Web.UI.WebControls.TextBox txttemp1;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
