//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xiaoHOUSE.Web.userInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lbluserName;
		protected global::System.Web.UI.WebControls.TextBox txtnickName;
		protected global::System.Web.UI.WebControls.TextBox txtuserRoles;
		protected global::System.Web.UI.WebControls.TextBox txtregisterDate;
		protected global::System.Web.UI.WebControls.TextBox txtregisterIP;
		protected global::System.Web.UI.WebControls.TextBox txtlastLoginDate;
		protected global::System.Web.UI.WebControls.TextBox txtlastLoginIP;
		protected global::System.Web.UI.WebControls.TextBox txtsex;
		protected global::System.Web.UI.WebControls.TextBox txtEmail;
		protected global::System.Web.UI.WebControls.TextBox txtage;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
